name: pvsnp_env
channels:
  - defaults
dependencies:
  - cython=0.29
  - jupyter=1.0.0
  - networkx=2.2
  - numpy=1.15.4
  - pandas=0.23.4
  - python=3.7.1
  - scikit-learn=0.20.1
  - seaborn=0.9.0
  - nbformat=4.4.0
